// main file - executable code ONLY
// Simridhi Sharma, Jonathan Rivera
// EVERYTHING HIGHLIGHTED WITH "**ADDED" OR "**CHANGED" IS AI GENERATED BY CLAUDE.AI
// unedit version of code is commented out below

#include "account.h"
#include "Menu.h"
#include "Cart.h"
#include "DeliveryPerson.h"
#include <iostream>
using namespace std;

// function to display main menu (Jonathan)
void displayMainMenu() {
    cout << "==== Welcome to Our Food Delivery Service! ====\n";
    cout << "\n";
    cout << "Would You Like To:\n";
    cout << "1. Create An Account\n";
    cout << "2. Login to Account\n";
    cout << "3. Exit\n";
    cout << "\n";
    cout << "Choice: ";
}

// function to display user menu (Jonathan)
void userMenu() {
    cout << "==== User Menu ====\n";
    cout << "\n";
    cout << "Would You Like To:\n";
    cout << "1. View Restaurant Menu\n";
    cout << "2. Add/Remove Items from Your Cart\n";
    cout << "3. View Cart\n";                          // **ADDED: New option to view cart**
    cout << "4. Checkout\n";                           // **ADDED: New option to checkout**
    cout << "5. Logout from Account\n";                // **CHANGED: Updated numbering**
    cout << "6. Exit\n";                               // **CHANGED: Updated numbering**
    cout << "\n";
    cout << "Choice: ";
}

int main() {
    // create AccountManager with file name for storing accounts
    AccountManager manager("userAccounts.txt");
    DeliveryPerson person("Teddy", "FordF150", "ABX-1X2", 12);
    // creates MenuDisplay and Cart objects for functions
    MenuDisplay display; 
    Cart cart1("Restaurant Name", 5);

    ofstream transactionHistory("transactionHistory.txt", ios::app);

    bool running = true;
    // loop condition runs so long as running is true
    while (running) {
        displayMainMenu();
        int choice;
        cin >> choice;
        cin.ignore(1000, '\n');                        // **ADDED: Clear input buffer** 

        // choosing between account creation and login
        if (choice == 1) {
            manager.handleAccountCreation();
        } else if (choice == 2) {
            // **CHANGED: Store login success status**
            string username, password;
            bool loggedIn = false;

            while (!loggedIn) {
                cout << "Enter username: ";
                cin >> username;
                cout << "Enter password: ";
                cin >> password;
                cin.ignore(1000, '\n');           

                if (manager.login(username, password)) {
                    cout << "Login successful!\n";
                    loggedIn = true;
                } else {
                    char retry;
                    cout << "Invalid credentials. Try again? (y/n): ";
                    cin >> retry;
                    cin.ignore(1000, '\n');     
                    if (retry != 'y' && retry != 'Y') {
                        cout << "Returning to main menu.\n";
                        break;
                    }
                }
            }

            // **CHANGED: Only proceed to user menu if login was successful**
            if (!loggedIn) {
                continue;
            }

            // After login, show user menu
            bool userLoggedIn = true;
            while (userLoggedIn) {
                // displays user menu, and allows users to choose
                userMenu();
                int userChoice;
                cin >> userChoice;
                cin.ignore(1000, '\n');           

                // choosing from user menus
                if (userChoice == 1) {
                    cout << "\n=== Restaurant Menu ===\n";
                    display.displayWholeMenu();
                    cout << "\n";                      // **ADDED: Better formatting**
                } else if (userChoice == 2) {
                    cout << "\n=== Manage Cart ===\n";
                    cart1.addOrRemove();
                    cout << "\n";                      // **ADDED: Better formatting**
                } else if (userChoice == 3) {          // **ADDED: View cart option**
                    cout << "\n=== Your Cart ===\n";
                    cout << cart1 << endl;
                    cout << "\n";
                } else if (userChoice == 4) {          // **ADDED: Checkout option**
                    cout << "\n=== Checkout ===\n";
                    cout << cart1 << endl;

                    char checkoutChoice;
                    cout << "Would you like to checkout? (y/n): ";
                    cin >> checkoutChoice;
                    cin.ignore(1000, '\n');

                    if (checkoutChoice == 'y' || checkoutChoice == 'Y') {
                        cart1.getTotal();
                        cart1.displayPrice();          // **ADDED: Display price breakdown**
                        cout << "\nOrder Complete!\n";
                        person.displayDeliveryInfo();

                        // **ADDED: Save transaction to file**
                        if (!transactionHistory.is_open()) {
                            cerr << "Error: Could not save transaction history.\n";
                        } else {
                            transactionHistory << cart1 << endl;
                            cout << "Transaction saved to history.\n";
                        }

                        userLoggedIn = false;          // **ADDED: Logout after checkout**
                    } else {
                        cout << "Checkout cancelled.\n";
                    }
                    cout << "\n";
                } else if (userChoice == 5) {          // **CHANGED: Updated from 3 to 5**
                    cout << "Logging out...\n";
                    userLoggedIn = false;
                } else if (userChoice == 6) {          // **CHANGED: Updated from 4 to 6**
                    cout << "Exiting program...\n";
                    userLoggedIn = false;
                    running = false;
                } else {
                    cout << "Invalid choice. Try again.\n";
                }
            }
        } else if (choice == 3) {
            cout << "Exiting program...\n";
            running = false;
        } else {
            cout << "Invalid choice. Try again.\n";
        }
    }

    // **REMOVED: Duplicate checkout code that was unreachable**

    transactionHistory.close();                        // **ADDED: Properly close file**
    cout << "Thank you for using our service!\n";     // **ADDED: Goodbye message**

    return 0;
}



// // main file - executable code ONLY
// // Simridhi Sharma (add your names here)

// #include "account.h"
// #include "Menu.h"
// #include "Cart.h"
// #include "DeliveryPerson.h"
// #include <iostream>
// using namespace std;

// void displayMainMenu() {
//     cout << "==== Welcome to Our Food Delivery Service! ====\n";
//     cout << "\n";
//     cout << "Would You Like To:\n";
//     cout << "1. Create An Account\n";
//     cout << "2. Login to Account\n";
//     cout << "3. Exit\n";
//     cout << "\n";
//     cout << "Choice: ";
// }

// void userMenu() {
//     cout << "==== User Menu ====\n";
//     cout << "\n";
//     cout << "Would You Like To:\n";
//     cout << "1. View Restaurant Menu\n";
//     cout << "2. Add/Remove Items from Your Cart\n";
//     cout << "3. Logout from Account\n";
//     cout << "4. Exit\n";   
//     cout << "\n";
//     cout << "Choice: ";
// }

// int main() {
//     // create AccountManager with file name for storing accounts
//     AccountManager manager("userAccounts.txt");
//     DeliveryPerson person ("Teddy", "FordF150", "ABX-1X2", 12);
//     // creates MenuDisplay and Cart objects for functions
//     MenuDisplay display; 
//     Cart cart1 ("Restaurant Name", 5);

//     ofstream transactionHistory("transactionHistory.txt", ios::app);


//     bool running = true;
//     // loop condition runs so long as running is true
//     while (running) {
//         displayMainMenu();
//         int choice;
//         cin >> choice;

//         // choosing between acccount creation and login
//         if (choice == 1) {
//             manager.handleAccountCreation();
//         } else if (choice == 2) {
//             manager.handleLogin();

//             // After login, show user menu
//             bool userLoggedIn = true;
//             while (userLoggedIn) {
//                 // displays user menu, and allows users to choose
//                 userMenu();
//                 int userChoice;
//                 cin >> userChoice;

//                 // choosing from user menus
//                 if (userChoice == 1) {
//                     cout << "Displaying restaurant menu...\n";
//                     display.displayWholeMenu();
//                 } else if (userChoice == 2) {
//                     cout << "Add/Remove items from cart...\n";
//                     cart1.addOrRemove();
//                 } else if (userChoice == 3) {
//                     cout << "Logging out...\n";
//                     userLoggedIn = false; // logs out of account
//                 } else if (userChoice == 4) {
//                     cout << "Exiting program...\n";
//                     userLoggedIn = false; // logs out of account
//                     running = false; // exits entire program
//                 } else {
//                     cout << "Invalid choice. Try again.\n";
//                 }
//             }
//             // exits program if choice is three
//         } else if (choice == 3) {
//             cout << "Exiting program...\n";
//             running = false;
//             return 0;
//         } else {
//             cout << "Invalid choice. Try again.\n";
//         }
//     }

//     int choice {0};
//     cout << cart1 <<  endl;
//     cart1.displayPrice();
//     cout << "Would you like to checkout (y/n)?";
//     cin >> choice;
//     cin.ignore(1000, '\n');
    
//     if (choice == 'y' || choice == 'Y') {
//         cout << "Order Complete!" << endl;
//         person.displayDeliveryInfo();

//         if (!transactionHistory.is_open()) {
//             cerr << "Error. Program Finished.";
//             exit(EXIT_FAILURE);
//         } else {
//             transactionHistory << cart1 << endl;
//         }
        
//     } else if (choice == 'n' || choice == 'N') {
//         cout << "Oh Well. Thanks Anyway!";
//     }

//     return 0;
// }
